import { useEffect, useRef, useState } from 'react'
import { Activity, AlertTriangle, BarChart3, BookOpenCheck, ChevronRight, CircleUserRound, Download, FileCheck2, FileSearch, LogOut, Menu, Moon, Network, PanelLeftClose, Search, ShieldCheck, Sun, UploadCloud, UsersRound, X } from 'lucide-react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import '@xyflow/react/dist/style.css'
import { api, Claim, setCsrf, User } from './api'
import { ClaimDetail } from './ClaimExperience'
import { Imports } from './ImportExperience'
import { NetworkDetail, Networks as NetworkList } from './NetworkExperience'
import { Audit as TrustAudit, Reports as TrustReports } from './TrustExperience'
import { Claims, Overview as WorkflowOverview, ProviderDetail as PopulationProviderDetail, Providers as PopulationProviders } from './PopulationExperience'
import { RuleDetail, Rules as CatalogueRules } from './CatalogueExperience'

const money = new Intl.NumberFormat('en-AE', { style: 'currency', currency: 'AED', maximumFractionDigits: 2 })
const nav = [
  ['/', 'Overview', BarChart3], ['/claims', 'Claims', FileSearch], ['/providers', 'Providers', UsersRound],
  ['/networks', 'Networks', Network], ['/imports', 'Upload & validation', UploadCloud], ['/rules', 'Rules & configuration', BookOpenCheck],
  ['/reports', 'Reports', Download], ['/audit', 'Audit log', ShieldCheck],
] as const

// Retained only to avoid discarding the user's earlier prototype implementations.
void [Providers, ProviderDetail, Rules, Networks]

function Status({ children, tone = 'neutral' }: { children: React.ReactNode; tone?: string }) { return <span className={`status ${tone}`}><span aria-hidden="true" className="status-dot" />{children}</span> }
function Empty({ title, reason, action }: { title: string; reason: string; action: string }) { return <div className="empty"><FileCheck2 size={24}/><h3>{title}</h3><p>{reason}</p><span>{action}</span></div> }
function Loading() { return <div className="skeletons" aria-label="Loading"><span/><span/><span/></div> }
function ErrorNotice({ message }: { message: string }) { return <div className="notice error"><AlertTriangle size={17}/><div><strong>Something needs attention</strong><p>{message}</p></div></div> }
function DataWindow() { const {data}=useFetch<any>('/data/profile',null); const label=(value?:string)=>value?new Date(`${value}T00:00:00`).toLocaleDateString('en-AE',{day:'2-digit',month:'short',year:'numeric'}):'—'; return <div className="header-context"><span>Loaded data window</span><strong>{label(data?.period_start)} — {label(data?.period_end)}</strong></div> }

function Login({ onLogin }: { onLogin: (u: User) => void }) {
  const [username, setUsername] = useState('admin'); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const result = await api<User & { csrf_token: string }>('/auth/login', { method: 'POST', body: JSON.stringify({ username, password }) }); setCsrf(result.csrf_token); onLogin(result) } catch (err) { setError((err as Error).message) } finally { setBusy(false) } }
  return <main className="login-shell"><section className="login-copy"><div className="wordmark">shahai</div><div className="framed-line"><span>01</span><i/></div><p className="eyebrow">Medical payment integrity</p><h1>Clear evidence.<br/>Controlled decisions.</h1><p>Evaluate tokenized UAE medical claims locally across hard edits, expert controls, peer signals, and explicit networks.</p><div className="trust"><ShieldCheck/><span>Runs on this computer. No cloud services or telemetry.</span></div></section><section className="login-card"><form onSubmit={submit}><div><p className="eyebrow">Secure local access</p><h2>Sign in</h2><p>Use one of the two accounts configured during setup.</p></div><label>Username<input value={username} onChange={e => setUsername(e.target.value)} autoComplete="username" required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" required /></label>{error && <ErrorNotice message={error}/>}<button className="primary" disabled={busy}>{busy ? 'Checking credentials…' : 'Open workspace'}<ChevronRight size={17}/></button><p className="fine">Decision-support proof of concept. A signal is not a fraud finding.</p></form></section></main>
}

function ApiHealth(){const[state,setState]=useState<'checking'|'ready'|'degraded'|'unavailable'>('checking');useEffect(()=>{let live=true;const check=()=>api<{status:string}>('/health').then(result=>{if(live)setState(result.status==='ready'?'ready':result.status==='degraded'?'degraded':'unavailable')}).catch(()=>{if(live)setState('unavailable')});check();const timer=window.setInterval(check,15000);return()=>{live=false;window.clearInterval(timer)}},[]);return <span className={`connection ${state==='unavailable'?'unavailable':state==='degraded'?'degraded':''}`} role="status"><i/>{state==='checking'?'Checking local API…':state==='ready'?'Local API ready':state==='degraded'?'Local API connected · degraded':'Local API unavailable'}</span>}

function Shell({ user, logout }: { user: User; logout: () => void }) {
  const location = useLocation(); const [collapsed, setCollapsed] = useState(false); const [theme, setTheme] = useState(localStorage.getItem('theme') ?? 'dark'); const [mobile, setMobile] = useState(false); const [narrow,setNarrow]=useState(()=>window.matchMedia('(max-width:760px)').matches); const menuButton=useRef<HTMLButtonElement>(null); const drawer=useRef<HTMLElement>(null)
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('theme', theme) }, [theme])
  useEffect(()=>{const query=window.matchMedia('(max-width:760px)');const update=()=>setNarrow(query.matches);query.addEventListener('change',update);return()=>query.removeEventListener('change',update)},[])
  useEffect(()=>{const label=nav.find(([path])=>path==='/'?location.pathname==='/':location.pathname.startsWith(path))?.[1]??'Workspace';document.title=`${label} · Shahai Medical Integrity`;window.requestAnimationFrame(()=>document.querySelector<HTMLElement>('#main-content')?.focus())},[location.pathname])
  useEffect(()=>{if(!mobile)return;drawer.current?.querySelector<HTMLElement>('button,a')?.focus();const onKey=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMobile(false);menuButton.current?.focus();return}if(event.key!=='Tab'||!drawer.current)return;const focusable=[...drawer.current.querySelectorAll<HTMLElement>('a,button:not([disabled])')];if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[mobile])
  const section=nav.find(([path])=>path==='/'?location.pathname==='/':location.pathname.startsWith(path));const detail=location.pathname.split('/').filter(Boolean).length>1
  return <div className={`app ${collapsed ? 'collapsed' : ''}`}>
    <a className="skip-link" href="#main-content">Skip to main content</a>
    {mobile&&<button className="drawer-backdrop" aria-label="Close navigation" onClick={()=>{setMobile(false);menuButton.current?.focus()}}/>}
    <aside ref={drawer} className={mobile ? 'mobile-open' : ''} aria-hidden={narrow&&!mobile?true:undefined} inert={narrow&&!mobile?true:undefined}>
      <div className="brand"><span className="wordmark">shahai</span><button className="icon-button close-mobile" onClick={() => {setMobile(false);menuButton.current?.focus()}} aria-label="Close navigation"><X/></button></div>
      <div className="product-name"><Activity size={16}/><span>Medical integrity</span></div>
      <nav aria-label="Primary navigation">{nav.map(([path, label, Icon]) => <Link key={path} to={path} onClick={() => setMobile(false)} className={location.pathname === path || (path!=='/'&&location.pathname.startsWith(`${path}/`)) ? 'active' : ''}><Icon/><span>{label}</span></Link>)}</nav>
      <div className="side-foot"><div className="role-card"><CircleUserRound/><div><strong>{user.username}</strong><span>{user.role}</span></div></div><button onClick={logout}><LogOut/><span>Sign out</span></button></div>
    </aside>
    <div className="content"><header><button ref={menuButton} className="icon-button mobile-menu" onClick={() => setMobile(true)} aria-label="Open navigation" aria-expanded={mobile}><Menu/></button><button className="icon-button collapse-button" onClick={() => setCollapsed(v => !v)} aria-label={collapsed ? 'Expand navigation' : 'Collapse navigation'}><PanelLeftClose/></button><DataWindow/><div className="header-actions"><ApiHealth/><button className="icon-button" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label="Toggle theme">{theme === 'dark' ? <Sun/> : <Moon/>}</button></div></header>
      {section&&<nav className="breadcrumbs" aria-label="Breadcrumb"><Link to={section[0]}>{section[1]}</Link>{detail&&<><span aria-hidden="true">/</span><span>Detail</span></>}</nav>}
      <Routes>
        <Route path="/" element={<WorkflowOverview/>}/><Route path="/claims" element={<Claims/>}/><Route path="/claims/:id" element={<ClaimDetail/>}/>
        <Route path="/providers" element={<PopulationProviders/>}/><Route path="/providers/:id" element={<PopulationProviderDetail/>}/>
        <Route path="/networks" element={<NetworkList/>}/><Route path="/networks/:id" element={<NetworkDetail/>}/><Route path="/imports" element={<Imports/>}/>
        <Route path="/rules" element={<CatalogueRules user={user}/>}/><Route path="/rules/:id" element={<RuleDetail user={user}/>}/>
        <Route path="/reports" element={<TrustReports/>}/><Route path="/audit" element={<TrustAudit/>}/><Route path="*" element={<Navigate to="/" replace/>}/>
      </Routes>
    </div>
  </div>
}

function Page({ eyebrow, title, description, actions, children }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode; children: React.ReactNode }) { return <main className="workspace"><div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div>{actions && <div className="page-actions">{actions}</div>}</div>{children}</main> }

function useFetch<T>(path: string, initial: T) { const [data, setData] = useState(initial); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { api<T>(path).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [path]); return { data, loading, error } }

export function LegacyOverview() {
  const { data, loading, error } = useFetch<{items: Claim[]; total: number}>('/claims?page_size=100', { items: [], total: 0 }); const flagged = data.items.filter(x => x.decision === 'Flagged'); const partial = data.items.filter(x => x.coverage === 'Partial'); const total = data.items.reduce((a, x) => a + Number(x.net_amount), 0)
  return <Page eyebrow="Operational overview" title="Payment-integrity picture" description="What needs attention, how much was evaluated, and where evidence is incomplete." actions={<Link className="button primary" to="/imports"><UploadCloud/>Load claims</Link>}>{error && <ErrorNotice message={error}/>}<section className="hero-grid"><article className="decision-panel"><div className="panel-head"><div><span>Current review population</span><Status tone={partial.length ? 'warning' : 'success'}>{partial.length ? 'Partial coverage' : 'Complete coverage'}</Status></div><strong>{loading ? '—' : data.total.toLocaleString()}</strong><p>claims in local history</p></div><div className="decision-split"><div><span className="signal-icon"><AlertTriangle/></span><div><strong>{flagged.length}</strong><span>Flagged</span></div></div><div><span className="clean-icon"><ShieldCheck/></span><div><strong>{Math.max(0, data.items.length - flagged.length)}</strong><span>No flag detected</span></div></div></div></article><article className="amount-panel"><p className="eyebrow">Associated value</p><strong>{money.format(total)}</strong><p>Net claim amount in the visible population. This is not confirmed exposure or savings.</p><div className="mini-bars" aria-label="Monthly associated value trend"><i style={{height:'32%'}}/><i style={{height:'48%'}}/><i style={{height:'43%'}}/><i style={{height:'66%'}}/><i style={{height:'58%'}}/><i style={{height:'79%'}}/><i style={{height:'70%'}}/></div></article></section><section className="two-col"><article className="panel"><div className="section-head"><div><p className="eyebrow">Priority queue</p><h2>Claims requiring review</h2></div><Link to="/claims">View all <ChevronRight/></Link></div>{loading ? <Loading/> : flagged.length ? <LegacyClaimTable rows={flagged.slice(0,5)} compact/> : <Empty title="No flagged claims yet" reason="No completed evaluation has produced an active signal." action="Load a demo or validated claim batch to begin."/>}</article><article className="panel"><div className="section-head"><div><p className="eyebrow">Coverage posture</p><h2>Catalogue readiness</h2></div></div><div className="coverage-list"><div><span><i className="ok"/>Structured executable</span><strong>149</strong></div><div><span><i className="wait"/>Deferred document</span><strong>12</strong></div><div><span><i className="off"/>Excluded model</span><strong>3</strong></div></div><p className="panel-note">Missing inputs disable applicable executable controls and make run coverage Partial. They never produce a clean pass.</p></article></section></Page>
}

export function LegacyClaimTable({ rows, compact = false }: { rows: Claim[]; compact?: boolean }) { return <div className={`table-wrap ${compact ? 'compact' : ''}`}><table><thead><tr><th>Decision</th><th>Claim</th><th>Service date</th><th>Provider</th><th>Primary reason</th><th className="num">Net amount</th><th>Coverage</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><Status tone={row.decision === 'Flagged' ? 'error' : 'success'}>{row.decision}</Status></td><td><Link className="claim-link" to={`/claims/${row.id}`}>{row.claim_id}</Link><small>{row.claim_type}</small></td><td>{row.service_date}</td><td>{row.provider}</td><td className="reason">{row.primary_reason}</td><td className="num">{money.format(Number(row.net_amount))}</td><td><Status tone={row.coverage === 'Partial' ? 'warning' : 'info'}>{row.coverage}</Status></td><td><Link className="icon-button" to={`/claims/${row.id}`} aria-label={`Open ${row.claim_id}`}><ChevronRight/></Link></td></tr>)}</tbody></table></div> }

function Providers(){const {data,loading,error}=useFetch<any>('/providers',{items:[]});return <Page eyebrow="Entity analytics" title="Providers" description="Volume, value, peer context, and contributing claims without turning a signal into a finding.">{error&&<ErrorNotice message={error}/>}<section className="panel">{loading?<Loading/>:data.items.length?<div className="table-wrap"><table><thead><tr><th>Provider</th><th className="num">Claims</th><th className="num">Associated amount</th><th>Peer support</th><th>Peer level used</th></tr></thead><tbody>{data.items.map((x:any)=><tr key={x.provider}><td><Link className="claim-link" to={`/providers/${x.provider}`}>{x.provider}</Link></td><td className="num">{x.claims}</td><td className="num">{money.format(Number(x.associated_amount))}</td><td><Status tone={x.support==='sufficient'?'success':'warning'}>{x.support}</Status><small>{x.peer_size} entities</small></td><td>{x.peer_level_used}<small>{x.limitation}</small></td></tr>)}</tbody></table></div>:<Empty title="No provider history" reason="Provider analytics need committed claim history." action="Load a claim batch with provider tokens."/>}</section></Page>}
function ProviderDetail(){const id=decodeURIComponent(location.pathname.split('/').pop()??'');const{data,loading,error}=useFetch<any>(`/providers/${encodeURIComponent(id)}`,null);if(loading)return <Page eyebrow="Provider intelligence" title="Loading provider" description="Calculating peer support and contribution links."><Loading/></Page>;if(error||!data)return <Page eyebrow="Provider intelligence" title="Provider unavailable" description="This provider could not be loaded."><ErrorNotice message={error}/></Page>;return <Page eyebrow="Provider intelligence" title={data.provider} description="Observed activity, explicit fallback peer context, and linked claim evidence."><div className="catalogue-strip"><div><span>Claims</span><strong>{data.metrics.claims}</strong></div><div><span>Associated value</span><strong>{money.format(Number(data.metrics.associated_amount))}</strong></div><div><span>Average claim</span><strong>{money.format(Number(data.metrics.average_claim))}</strong></div><div><span>Peer support</span><Status tone={data.peer.support==='sufficient'?'success':'warning'}>{data.peer.support}</Status></div></div><section className="two-col"><article className="panel"><p className="eyebrow">Trend</p><h2>Contributing claims over time</h2><div className="trend-bars">{data.trend.map((x:any)=><Link key={x.claim_id} to={`/claims/${x.claim_id}`} title={`${x.period}: ${money.format(Number(x.amount))}`} style={{height:`${Math.max(8,Math.min(100,Number(x.amount)/Math.max(...data.trend.map((v:any)=>Number(v.amount)))*100))}%`}}><span className="sr-only">{x.period} {x.amount}</span></Link>)}</div></article><article className="panel"><p className="eyebrow">Peer context</p><h2>{data.peer.level_used}</h2><dl className="evidence-grid"><div><dt>Peer entities</dt><dd>{data.peer.size}</dd></div><div><dt>Peer median value</dt><dd>{data.peer.median_associated_amount?money.format(Number(data.peer.median_associated_amount)):'Unavailable'}</dd></div></dl><p className="panel-note">Sparse peer populations abstain; they are never converted into a clean comparison.</p></article></section></Page>}
function Networks(){const {data,loading,error}=useFetch<any>('/networks',{items:[]});return <Page eyebrow="Explicit network analytics" title="Networks" description="Boundaries come only from supplied effective-dated network IDs; amounts count each claim once.">{error&&<ErrorNotice message={error}/>}<section className="panel">{loading?<Loading/>:data.items.length?<div className="network-grid">{data.items.map((x:any)=><Link aria-label={`Open network ${x.network_id}`} to={`/networks/${encodeURIComponent(x.network_id)}`} key={x.network_id}><article><Network/><div><span>Network</span><h3>{x.network_id}</h3></div><dl><div><dt>Distinct claims</dt><dd>{x.distinct_claims}</dd></div><div><dt>Associated value</dt><dd>{money.format(Number(x.distinct_associated_amount))}</dd></div></dl><p>Open the interactive evidence graph and accessible edge table.</p></article></Link>)}</div>:<Empty title="No explicit networks" reason="Network IDs were not supplied in committed claim history." action="Load provider_network data; boundaries are never inferred."/>}</section></Page>}

function Rules({user}:{user:User}){const[scope,setScope]=useState('');const[search,setSearch]=useState('');const path=`/rules?${scope?`scope_state=${scope}`:''}`;const{data,loading,error}=useFetch<any>(path,{items:[],catalogue:{total:164,executable:149,deferred:12,excluded:3}});const rows=data.items.filter((x:any)=>(x.rule_id+x.rule_name).toLowerCase().includes(search.toLowerCase()));return <Page eyebrow="Governed controls" title="Rules & configuration" description="All catalogue controls remain visible. Only executable rules can be configured, and changes apply prospectively." actions={<Status tone={user.role==='admin'?'info':'neutral'}>{user.role==='admin'?'Admin editing':'Read only'}</Status>}><div className="catalogue-strip"><div><span>Total catalogue</span><strong>164</strong></div><div><span>Executable</span><strong>149</strong></div><div><span>Deferred text</span><strong>12</strong></div><div><span>Excluded model</span><strong>3</strong></div></div><div className="toolbar"><label className="search"><Search/><span className="sr-only">Search rules</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ID or rule name"/></label><select aria-label="Filter by scope" value={scope} onChange={e=>setScope(e.target.value)}><option value="">All scope states</option><option value="EXECUTABLE">Executable</option><option value="DEFERRED_DOCUMENT">Deferred document</option><option value="EXCLUDED_MODEL">Excluded model</option></select><span className="result-count">{rows.length} controls</span></div>{error&&<ErrorNotice message={error}/>}<section className="panel table-panel">{loading?<Loading/>:<div className="table-wrap compact"><table><thead><tr><th>Control</th><th>Name</th><th>Type / stage</th><th>Scope</th><th>State</th><th>Reason code</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.rule_id}><td><Link className="claim-link" to={`/rules/${x.rule_id}`}>{x.rule_id}</Link><small>{x.scenario_id}</small></td><td className="reason">{x.rule_name}</td><td>{x.type_expression}<small>{x.canonical_stage??x.stage_label}</small></td><td><Status tone={x.scope_state==='EXECUTABLE'?'success':x.scope_state==='DEFERRED_DOCUMENT'?'warning':'neutral'}>{x.scope_state.replaceAll('_',' ')}</Status></td><td>{x.operational_state??'Locked'}</td><td><code>{x.reason_code}</code></td></tr>)}</tbody></table></div>}</section></Page>}

export function LegacyReports(){return <Page eyebrow="Reconciled outputs" title="Reports" description="Exports use the same local claim population and include scope, role, timestamp, and decision-support metadata."><section className="report-grid">{[['CSV','Flat claims export','csv'],['Excel','Multi-sheet operational workbook','xlsx'],['PDF','Printable batch summary','pdf']].map(([type,title,ext])=><article className="panel" key={type}><span className="report-icon"><Download/></span><p className="eyebrow">{type}</p><h2>{title}</h2><p>Includes current local records and stable identifiers. Spreadsheet output is protected against formula injection.</p><a className="button primary" href={`/api/v1/reports/${ext}`}>Generate {type}<ChevronRight/></a></article>)}</section><div className="notice info"><ShieldCheck/><div><strong>Interpretation boundary</strong><p>Gross associated value is not confirmed exposure or savings. Every export states that a signal is decision support, not a fraud finding.</p></div></div></Page>}
export function LegacyAudit(){const{data,loading,error}=useFetch<any[]>('/audit',[]);return <Page eyebrow="Accountability" title="Audit log" description="Security-relevant actions are append-only and exclude passwords and full sensitive payloads.">{error&&<ErrorNotice message={error}/>}<section className="panel">{loading?<Loading/>:data.length?<div className="timeline">{data.map(x=><div key={x.id}><i/><time>{new Date(x.created_at).toLocaleString()}</time><strong>{x.event_type.replaceAll('_',' ')}</strong><span>{x.target_type}{x.target_id?` · ${x.target_id}`:''}</span></div>)}</div>:<Empty title="No audited activity" reason="No sign-ins, imports, evaluations, exports, or configuration changes have been recorded." action="Operational actions will appear here automatically."/>}</section></Page>}

export default function App(){const[user,setUser]=useState<User|null>(null);const[checking,setChecking]=useState(true);const navigate=useNavigate();useEffect(()=>{api<User>('/auth/session').then(setUser).catch(()=>setUser(null)).finally(()=>setChecking(false))},[]);async function logout(){try{await api('/auth/logout',{method:'POST'})}finally{sessionStorage.removeItem('csrf');setUser(null);navigate('/')}}if(checking)return <div className="boot"><div className="wordmark">shahai</div><Loading/></div>;return user?<Shell user={user} logout={logout}/>:<Login onLogin={setUser}/>}
