import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, Download, ExternalLink, Network, ShieldCheck } from 'lucide-react'
import { Link, useLocation } from 'react-router-dom'
import { Background, Controls, ReactFlow } from '@xyflow/react'
import { api } from './api'

const money=new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',maximumFractionDigits:2})
function Loading(){return <div className="skeletons" aria-label="Loading"><span/><span/><span/></div>}
function Page({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <main id="main-content" className="workspace" tabIndex={-1}><Link className="back-link" to="/networks"><ArrowLeft/>Back to networks</Link><div className="page-title"><div><p className="eyebrow">Network review</p><h1>{title}</h1><p>{description}</p></div></div>{children}</main>}
function Empty(){return <div className="empty"><Network/><h3>No relationships match this view</h3><p>Choose all observed links or another review focus.</p></div>}

export function Networks(){const[data,setData]=useState<any>(null);const[error,setError]=useState('');useEffect(()=>{api('/networks').then(setData).catch(reason=>setError(reason.message))},[]);return <main id="main-content" className="workspace" tabIndex={-1}><div className="page-title"><div><p className="eyebrow">Observed network relationships</p><h1>Networks</h1><p>Start with scale, time period, and why a supplied administrative network may deserve review.</p></div></div>{error&&<div className="notice error" role="alert">{error}</div>}{!data?<Loading/>:<><div className="notice info"><ShieldCheck/><div><strong>Analysis boundary</strong><p>{data.methodology}</p></div></div><section className="network-list-grid">{data.items.map((item:any)=><article className="panel" key={item.network_id}><p className="eyebrow">Administrative network</p><h2>{item.network_id}</h2><p>{item.review_reason}</p><dl className="evidence-grid"><div><dt>Providers</dt><dd>{item.providers}</dd></div><div><dt>Members</dt><dd>{item.members}</dd></div><div><dt>Shared members</dt><dd>{item.shared_members}</dd></div><div><dt>Distinct claims</dt><dd>{item.distinct_claims}</dd></div><div><dt>Period</dt><dd>{item.period_start} to {item.period_end}</dd></div><div><dt>Claim value</dt><dd>{money.format(Number(item.distinct_associated_amount))}</dd></div></dl><p className="panel-note">Claim value is not suspected or confirmed loss.</p><Link className="button primary" aria-label={`Review relationships in ${item.network_id}`} to={`/networks/${encodeURIComponent(item.network_id)}`}>Review relationships</Link></article>)}</section></>}</main>}

export function NetworkDetail(){
  const id=decodeURIComponent(useLocation().pathname.split('/').pop()??'');const[data,setData]=useState<any>(null);const[error,setError]=useState('');const[focus,setFocus]=useState('all');const[selected,setSelected]=useState<any>(null)
  useEffect(()=>{api(`/networks/${encodeURIComponent(id)}`).then(setData).catch(reason=>setError(reason.message))},[id])
  const sharedMembers=useMemo(()=>{const providers=new Map<string,Set<string>>();for(const edge of data?.edges??[]){const member=edge.target.replace(/^member:/,'');const values=providers.get(member)??new Set<string>();values.add(edge.source);providers.set(member,values)}return new Set([...providers].filter(([,values])=>values.size>1).map(([member])=>member))},[data])
  const edges=useMemo(()=>{const all=data?.edges??[];if(focus==='shared')return all.filter((edge:any)=>sharedMembers.has(edge.target.replace(/^member:/,'')));if(focus==='high')return all.filter((edge:any)=>edge.claim_count>1);return all},[data,focus,sharedMembers])
  const visibleIds=useMemo(()=>new Set(edges.flatMap((edge:any)=>[edge.source,edge.target])),[edges]);const nodes=(data?.nodes??[]).filter((node:any)=>visibleIds.has(node.id))
  useEffect(()=>{const canvas=document.querySelector<HTMLElement>('.graph-panel');canvas?.setAttribute('aria-hidden','true');canvas?.querySelectorAll<HTMLElement>('button,[tabindex]').forEach(item=>item.tabIndex=-1)},[data,focus])
  if(error)return <Page title="Network unavailable" description="This network could not be loaded."><div className="notice error" role="alert">{error}</div></Page>
  if(!data)return <Page title="Loading network" description="Building observed claim relationships."><Loading/></Page>
  const providers=nodes.filter((node:any)=>node.type==='provider');const members=nodes.filter((node:any)=>node.type==='member')
  const flowNodes=[...providers.map((node:any,index:number)=>({id:node.id,position:{x:20,y:index*72},data:{label:`Provider ${node.key} · ${node.claims} claims`},className:'provider-node'})),...members.map((node:any,index:number)=>({id:node.id,position:{x:430,y:index*72},data:{label:`Member ${node.key} · ${node.claims} claims`},className:'member-node'}))]
  const flowEdges=edges.map((edge:any)=>({id:edge.id,source:edge.source,target:edge.target,label:`${edge.claim_count} claim${edge.claim_count===1?'':'s'}`,style:{strokeWidth:Math.max(1,Math.min(7,edge.claim_count))}}))
  return <Page title={data.network_id} description="Administrative network supplied in the claims file. Relationships are observed billing links, not evidence of coordination or wrongdoing.">
    <section className="network-explainer"><article className="panel network-guide"><p className="eyebrow">How to read this analysis</p><h2>Each line connects a provider to a member with a supporting claim</h2><ul><li>A thicker line means more claims between that provider and member.</li><li>“Shared member” means the member has claims from multiple providers in this network.</li><li>Use the evidence table to open the exact claims before drawing a conclusion.</li></ul></article><article className="panel metric-card"><span>Providers</span><strong>{data.metrics.provider_count.toLocaleString()}</strong><small>Provider concentration: {data.metrics.concentration}. The largest providers account for more activity when concentration is high.</small></article><article className="panel metric-card"><span>Members seen by multiple providers</span><strong>{data.metrics.multi_provider_members.toLocaleString()}</strong><small>Potential care pathways to review—not suspicious by itself.</small></article><article className="panel metric-card"><span>Total claim value</span><strong>{money.format(Number(data.metrics.distinct_associated_amount))}</strong><small>{data.metrics.distinct_claims.toLocaleString()} distinct claims; not suspected loss.</small></article></section>
    <section className="panel review-paths"><div className="section-head"><div><p className="eyebrow">What deserves review?</p><h2>Highest-volume provider–member links</h2></div><a className="button secondary" href={`/api/v1/networks/${encodeURIComponent(id)}/export.csv`}><Download/>Download full evidence</a></div><p>Ranked by number of distinct claims. High volume can have legitimate clinical explanations.</p><div className="relationship-cards">{data.insights.strongest_relationships.slice(0,6).map((item:any,index:number)=><button key={item.id} onClick={()=>setSelected(data.edges.find((edge:any)=>edge.id===item.id))}><span>{index+1}</span><div><strong>{item.source.replace(/^provider:/,'')} → {item.target.replace(/^member:/,'')}</strong><small>{item.claim_count} claims · {money.format(Number(item.associated_amount))}</small></div></button>)}</div></section>
    <div className="toolbar"><label>Review focus<select value={focus} onChange={event=>setFocus(event.target.value)}><option value="all">All displayed relationships</option><option value="shared">Members seen by multiple providers</option><option value="high">Links with more than one claim</option></select></label><span className="result-count">Displayed {edges.length.toLocaleString()} relationships and {nodes.length.toLocaleString()} people/providers from the readable subset; {data.display_summary.edges_total.toLocaleString()} relationships exist in the full network.</span></div>
    {data.truncated&&<div className="notice info"><ShieldCheck/><div><strong>Readable subset</strong><p>The graph shows {data.display_summary.nodes_shown.toLocaleString()} of {data.display_summary.nodes_total.toLocaleString()} people/providers and {data.display_summary.edges_shown.toLocaleString()} of {data.display_summary.edges_total.toLocaleString()} links. Summary totals use the full network.</p></div></div>}
    <section className="graph-layout"><article className="panel graph-panel" role="img" aria-label="Optional visual map of provider-to-member claim links"><ReactFlow nodes={flowNodes} edges={flowEdges} fitView fitViewOptions={{padding:0.2}} nodesDraggable={false} nodesFocusable={false} edgesFocusable={false} elementsSelectable={false} onInit={instance=>requestAnimationFrame(()=>instance.fitView({padding:0.2}))}><Controls showInteractive={false}/><Background/></ReactFlow></article><aside className="panel"><p className="eyebrow">Selected evidence</p>{selected?<><h2>{selected.key??'Provider–member link'}</h2><dl className="evidence-grid"><div><dt>Claims</dt><dd>{selected.claims??selected.claim_count}</dd></div><div><dt>Associated value</dt><dd>{money.format(Number(selected.amount??selected.associated_amount??0))}</dd></div></dl>{selected.claim_evidence?.map((claim:any)=><Link className="selected-claim" key={claim.id} to={`/claims/${claim.id}`}>{claim.claim_id}<span>{claim.service_date} · {money.format(Number(claim.net_amount))}</span><ExternalLink/></Link>)}</>:<p>Select a ranked relationship card or evidence-table row.</p>}</aside></section>
    <section className="panel"><div className="section-head"><div><p className="eyebrow">Accessible evidence</p><h2>Provider–member relationships and supporting claims</h2></div></div>{edges.length?<div className="table-wrap"><table><thead><tr><th>Provider</th><th>Member</th><th className="num">Claims</th><th className="num">Associated value</th><th>Supporting claims</th></tr></thead><tbody>{edges.map((edge:any)=><tr key={edge.id}><td>{edge.source.replace(/^provider:/,'')}</td><td>{edge.target.replace(/^member:/,'')}</td><td className="num">{edge.claim_count}</td><td className="num">{money.format(Number(edge.associated_amount))}</td><td>{edge.claim_evidence.map((claim:any)=><Link key={claim.id} className="claim-link" to={`/claims/${claim.id}`}>{claim.claim_id}<small>{claim.service_date} · {money.format(Number(claim.net_amount))}</small></Link>)}</td></tr>)}</tbody></table></div>:<Empty/>}</section>
  </Page>
}
