/* eslint-disable react-hooks/set-state-in-effect */
import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, ChevronRight, Download, FileCheck2, ShieldCheck } from 'lucide-react'
import { api } from './api'

function Page({eyebrow,title,description,children}:{eyebrow:string;title:string;description:string;children:React.ReactNode}){return <main id="main-content" className="workspace" tabIndex={-1}><div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></div>{children}</main>}
function Loading(){return <div className="skeletons" aria-label="Loading"><span/><span/><span/></div>}
function ErrorNotice({message}:{message:string}){return <div className="notice error" role="alert"><AlertTriangle/><div><strong>Something needs attention</strong><p>{message}</p></div></div>}
function Status({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`status ${tone}`}><span aria-hidden="true" className="status-dot"/>{children}</span>}

type Preview={total_claims:number;assessed_claims:number;flagged_claims:number;unevaluated_claims:number;partial_claims:number;scope:{description:string;batch_id?:number;run_id?:number;decision?:string;coverage?:string;provider?:string;query?:string;date_from?:string;date_to?:string};available_batches:{id:number;filename:string}[];available_runs:{id:number;batch_id:number;analysis_date:string;status:string}[]}

function ExportButton({ext,label,query,disabled}:{ext:string;label:string;query:string;disabled:boolean}){
  const[status,setStatus]=useState('')
  async function download(){
    setStatus('Preparing download…')
    try{
      const response=await fetch(`/api/v1/reports/${ext}?${query}`,{credentials:'include'})
      if(!response.ok)throw new Error((await response.text())||`Export failed (${response.status})`)
      const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement('a')
      link.href=url;link.download=ext==='xlsx'?'claims.xlsx':ext==='pdf'?'summary.pdf':'claims.csv';link.click();URL.revokeObjectURL(url)
      setStatus('Download ready')
    }catch(reason){setStatus((reason as Error).message)}
  }
  return <div><button className="primary" disabled={disabled||status==='Preparing download…'} onClick={download}>Generate {label}<ChevronRight/></button><span className="export-status" role="status">{disabled?'No matching claims to export':status}</span></div>
}
export function Reports(){
  const[batch,setBatch]=useState('');const[run,setRun]=useState('');const[decision,setDecision]=useState('')
  const[data,setData]=useState<Preview|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true)
  const query=useMemo(()=>{const p=new URLSearchParams();if(batch)p.set('batch_id',batch);if(run)p.set('run_id',run);if(decision)p.set('decision',decision);return p.toString()},[batch,run,decision])
  useEffect(()=>{setLoading(true);api<Preview>(`/reports/preview?${query}`).then(value=>{setData(value);setError('')}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[query])
  const runs=data?.available_runs.filter(item=>!batch||String(item.batch_id)===batch)??[]
  const formats=[{type:'CSV',title:'Claim-level data',description:'One row per selected claim, with assessment, coverage, supporting rules, immutable run snapshot hash, timestamp, role, and scope.',ext:'csv'},{type:'Excel',title:'Operational workbook',description:'Selected claims, report metadata, immutable run snapshots, and separately labelled local configuration history.',ext:'xlsx'},{type:'PDF',title:'Management summary',description:'Selected population counts with scope, immutable run snapshot hash, and decision-support boundary.',ext:'pdf'}]
  return <Page eyebrow="Reconciled outputs" title="Reports" description="Choose one population, preview exact counts, then export the same scope with consistent provenance.">
    <section className="panel report-controls"><div className="filter-grid"><label>Batch<select value={batch} onChange={event=>{setBatch(event.target.value);setRun('')}}><option value="">All committed batches</option>{data?.available_batches.map(item=><option key={item.id} value={item.id}>#{item.id} · {item.filename}</option>)}</select></label><label>Evaluation run<select value={run} onChange={event=>{setRun(event.target.value);const selected=data?.available_runs.find(item=>String(item.id)===event.target.value);if(selected)setBatch(String(selected.batch_id))}}><option value="">Latest completed run per selected batch</option>{runs.map(item=><option key={item.id} value={item.id}>Run #{item.id} · analysis {item.analysis_date}</option>)}</select></label><label>Decision population<select value={decision} onChange={event=>setDecision(event.target.value)}><option value="">All decisions</option><option value="Flagged">Review needed</option><option value="No flag detected">No signal in runnable controls</option><option value="Not evaluated">Not evaluated</option></select></label></div></section>
    {error&&<ErrorNotice message={error}/>} {loading||!data?<Loading/>:<><section className="panel report-scope"><div><p className="eyebrow">Export preview</p><h2>{data.scope.description}</h2><p>Batch: {data.scope.batch_id??'all'} · run: {data.scope.run_id??'latest completed per batch'} · decision: {data.scope.decision??'all'}</p></div><dl className="evidence-grid"><div><dt>Total claims</dt><dd>{data.total_claims.toLocaleString()}</dd></div><div><dt>Assessed</dt><dd>{data.assessed_claims.toLocaleString()}</dd></div><div><dt>Review needed</dt><dd>{data.flagged_claims.toLocaleString()}</dd></div><div><dt>Not evaluated</dt><dd>{data.unevaluated_claims.toLocaleString()}</dd></div><div><dt>Limited coverage</dt><dd>{data.partial_claims.toLocaleString()}</dd></div></dl></section><section className="report-grid">{formats.map(item=><article className="panel" key={item.type}><span className="report-icon"><Download/></span><p className="eyebrow">{item.type}</p><h2>{item.title}</h2><p>{item.description}</p><ExportButton ext={item.ext} label={item.type} query={query} disabled={data.total_claims===0}/></article>)}</section></>}
    <div className="notice info"><ShieldCheck/><div><strong>Interpretation boundary</strong><p>Associated values and rule estimates are decision support. They are not confirmed loss, savings, overpayment, or recoverable value.</p></div></div>
  </Page>
}

const ACTIONS:Record<string,string>={IMPORT_VALIDATED:'Validated an import',IMPORT_COMMITTED:'Committed an import',EVALUATION_QUEUED:'Queued an assessment run',EVALUATION_COMPLETED:'Completed an assessment run',CONFIGURATION_CHANGED:'Changed a rule configuration',REPORT_EXPORTED:'Exported a report',AUTH_LOGIN_SUCCEEDED:'Signed in',AUTH_LOGIN_FAILED:'Failed sign-in attempt',AUTH_LOGOUT:'Signed out',SYNTHETIC_DATASET_COMMITTED:'Loaded the synthetic engineering fixture'}
type AuditData={items:any[];total:number;page:number;page_size:number;event_types:string[];retention_note:string}
export function Audit(){const[page,setPage]=useState(1);const[type,setType]=useState('');const[actor,setActor]=useState('');const[data,setData]=useState<AuditData|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const query=useMemo(()=>{const p=new URLSearchParams({page:String(page),page_size:'50'});if(type)p.set('event_type',type);if(actor)p.set('actor',actor);return p.toString()},[page,type,actor]);useEffect(()=>{setLoading(true);api<AuditData>(`/audit/events?${query}`).then(value=>{setData(value);setError('')}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[query]);const pages=Math.max(1,Math.ceil((data?.total??0)/50));return <Page eyebrow="Accountability" title="Audit log" description="A paginated, human-readable record of local imports, assessments, configuration decisions, exports, and access events."><section className="panel filter-panel"><div className="filter-grid"><label>Action type<select value={type} onChange={event=>{setType(event.target.value);setPage(1)}}><option value="">All actions</option>{data?.event_types.map(item=><option key={item}>{item}</option>)}</select></label><label>Person<input value={actor} onChange={event=>{setActor(event.target.value);setPage(1)}} placeholder="Username"/></label></div><div className="filter-footer"><span>{data?.total.toLocaleString()??'—'} matching events</span><button className="secondary compact-button" onClick={()=>{setType('');setActor('');setPage(1)}}>Clear filters</button></div></section>{error&&<ErrorNotice message={error}/>} {loading||!data?<Loading/>:data.items.length?<><section className="panel audit-table"><div className="table-wrap"><table><thead><tr><th>When</th><th>Person</th><th>Action</th><th>Object</th><th>Outcome</th><th>Recorded change</th></tr></thead><tbody>{data.items.map(item=><tr key={item.id}><td>{new Date(item.created_at).toLocaleString('en-AE',{timeZone:'Asia/Dubai'})}<small>Asia/Dubai</small></td><td>{item.actor}<small>{item.actor_role??'system'}</small></td><td>{ACTIONS[item.event_type]??item.event_type.replaceAll('_',' ').toLowerCase()}<small>{item.event_type}</small></td><td>{item.target_type}{item.target_id?` · ${item.target_id}`:''}</td><td><Status tone={item.outcome==='Failed'?'error':'success'}>{item.outcome}</Status></td><td>{Object.keys(item.details).length?<details><summary>View recorded details</summary><pre>{JSON.stringify(item.details,null,2)}</pre></details>:'No additional details recorded'}</td></tr>)}</tbody></table></div></section><nav className="pagination" aria-label="Audit pagination"><button className="secondary" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Previous</button><span>Page {page} of {pages} · {data.retention_note}</span><button className="secondary" disabled={page>=pages} onClick={()=>setPage(value=>value+1)}>Next</button></nav></>:<div className="empty"><FileCheck2/><h3>No matching activity</h3><p>No audit event matches the selected filters.</p></div>}</Page>}
